version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    env_file:
      - server/server.env

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    env_file:
      - client/client.env
    depends_on:
      - server